site_name: Real Eyes, Realise
nav:
  - Home: index.md
  - Education: stereotypes.md
  - About: about.md
  - Organizations: organizations.md
  - Quiz: quiz.md
  - What to do with the bottle: recycling.md
  - Our Future: future.md
theme:
  name: material
  logo: logo/smalllogo.png
  icon: 
    logo: logo/smalllogo.png
  favicon: logo/smalllogo.png
  palette:
    scheme: default
    primary: 'black'
    accent: 'white'
extra:
  analytics:
    provider: google
    property: G-CMNQKDMWQF
